routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@manageRedirect');

Route::get('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();


Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth.admin']], function() {

    Route::get('', 'Dashboard\DashboardController@dashboard');
    Route::get('dashboard', 'Dashboard\DashboardController@index')->name('dashboard');

    Route::get('settings', 'Setting\SettingsController@index')->name('settings');
    Route::post('settings', 'Setting\SettingsController@store')->name('store_settings');
    Route::post('settings/{siteSetting}', 'Setting\SettingsController@update')->name('update_settings');

    Route::group(['prefix' => 'clients', 'as' => 'clients.', 'namespace' => 'Client'], function() {

        Route::get('/', 'ClientsController@index')->name('index');

        Route::get('create', 'ClientsController@create')->name('create');
        Route::post('create', 'ClientsController@store')->name('store');

        Route::get('edit/{client}', 'ClientsController@edit')->name('edit');
        Route::post('edit/{client}', 'ClientsController@update')->name('update');

        Route::get('delete/{client}', 'ClientsController@destroy')->name('destroy');

        Route::post('client/ajax', 'ClientsController@clientAjax')->name('client-ajax');

    });

    Route::group(['prefix' => 'cities', 'as' => 'cities.', 'namespace' => 'City'], function() {

        Route::get('/', 'CitiesController@index')->name('index');

        Route::get('create', 'CitiesController@create')->name('create');
        Route::post('create', 'CitiesController@store')->name('store');

        Route::get('edit/{city}', 'CitiesController@edit')->name('edit');
        Route::post('edit/{city}', 'CitiesController@update')->name('update');

        Route::get('delete/{city}', 'CitiesController@destroy')->name('destroy');

    });

    Route::group(['prefix' => 'permits', 'as' => 'permits.', 'namespace' => 'Permit'], function() {

        Route::get('/', 'PermitsController@index')->name('index');

        Route::get('create', 'PermitsController@create')->name('create');
        Route::post('create', 'PermitsController@store')->name('store');

        Route::get('edit/{permit}', 'PermitsController@edit')->name('edit');
        Route::post('edit/{permit}', 'PermitsController@update')->name('update');

        Route::get('delete/{permit}', 'PermitsController@destroy')->name('destroy');

    });

    Route::group(['prefix' => 'permit-categories', 'as' => 'permit_categories.', 'namespace' => 'Permit'], function() {

        Route::get('/', 'PermitCategoriesController@index')->name('index');

        Route::post('quick-create', 'PermitCategoriesController@quickCreate')->name('quick-create');

        Route::get('create', 'PermitCategoriesController@create')->name('create');
        Route::post('create', 'PermitCategoriesController@store')->name('store');

        Route::get('edit/{permitCategory}', 'PermitCategoriesController@edit')->name('edit');
        Route::post('edit/{permitCategory}', 'PermitCategoriesController@update')->name('update');

        Route::get('delete/{permitCategory}', 'PermitCategoriesController@destroy')->name('destroy');

    });

    Route::group(['prefix' => 'users', 'as' => 'users.', 'namespace' => 'User'], function() {

        Route::get('/', 'UsersController@index')->name('index');

        Route::get('create', 'UsersController@create')->name('create');
        Route::post('create', 'UsersController@store')->name('store');

        Route::get('edit/{user}', 'UsersController@edit')->name('edit');
        Route::post('edit/{user}', 'UsersController@update')->name('update');

        Route::get('delete/{user}', 'UsersController@destroy')->name('destroy');

    });

    Route::group(['prefix' => 'projects', 'as' => 'projects.', 'namespace' => 'Project'], function() {

        Route::get('/', 'ProjectsController@index')->name('index');

        Route::get('client-projects/{client}', 'ProjectsController@viewByClient')->name('byClient');

        Route::get('{client}/create', 'ProjectsController@createByClient')->name('createByClient');
        Route::post('{client}/create', 'ProjectsController@storeByClient')->name('createByClient');

        Route::get('create', 'ProjectsController@create')->name('create');
        Route::post('create', 'ProjectsController@store')->name('store');

        Route::get('edit/{project}', 'ProjectsController@edit')->name('edit');
        Route::post('edit/{project}', 'ProjectsController@update')->name('update');

        Route::get('delete/{project}', 'ProjectsController@destroy')->name('destroy');

        Route::post('ajax', 'ProjectsController@permitAjax')->name('permit-ajax');

        Route::post('send-notif', 'ProjectsController@ajaxSendNotification')->name('sendNotif');

        Route::post('delete/file', 'ProjectsController@ajaxDeleteFile')->name('delete-file');

    });

    Route::group(['prefix' => 'reports', 'as' => 'reports.', 'namespace' => 'Report'], function() {

        Route::get('projects-created-per-permit-category', 'ReportsController@projectsPerCategory')->name('projPerCategory');

        Route::get('projects-created', 'ReportsController@viewProjectsCreated')->name('projCreated');

        Route::get('projects-per-city', 'ReportsController@projectsPerCity')->name('projPerCity');

        Route::get('projects-per-status', 'ReportsController@projectsPerStatus')->name('projPerStatus');

    });

});

Route::group(['prefix' => 'client', 'as' => 'client.', 'namespace' => 'Client', 'middleware' => ['auth.client']], function() {

    Route::get('', 'Project\ProjectsController@dashboard')->name('dashboard');

    Route::get('profile', 'User\ProfileController@edit')->name('profile');
    Route::post('profile/{client}', 'User\ProfileController@update')->name('update');

    Route::group(['prefix' => 'projects', 'as' => 'projects.', 'namespace' => 'Project'], function() {

        Route::get('/', 'ProjectsController@index')->name('index');

        Route:: get('view/{project}', 'ProjectsController@viewProject')->name('view');
    });

});

Route::group(['prefix' => 'master-client', 'as' => 'master_client.', 'namespace' => 'MasterClient', 'middleware' => ['auth.master_client']], function() {

    Route::get('', 'Dashboard\DashboardController@dashRedirect')->name('dash-redirect');

    Route::get('dashboard', 'Dashboard\DashboardController@dashboard')->name('dashboard');

    Route::get('profile', 'User\ProfileController@edit')->name('profile');
    Route::post('profile/{client}', 'User\ProfileController@update')->name('update');

    Route::get('clients', 'Dashboard\DashboardController@index')->name('clients');

});

app/Http/Controllers/Admin/Client/ClientsController.php
<?php

namespace App\Http\Controllers\Admin\Client;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Http\Controllers\Controller;
use PermitExpress\Client\Client;
use PermitExpress\Client\ClientRepository;
use PermitExpress\ClientMasterProject\ClientMasterProject;
use PermitExpress\ClientMasterProject\ClientMasterProjectRepository;
use PermitExpress\User\User;
use PermitExpress\User\UserRepository;
use PermitExpress\Project\Project;
use PermitExpress\Project\ProjectRepository;
use PermitExpress\Validation\ValidationException;

class ClientsController extends Controller
{
    //
    public function __construct(
        ClientRepository $clientRepo,
        ProjectRepository $projectRepo,
        ClientMasterProjectRepository $masterProjRepo
    )
    {
        $this->clientRepo = $clientRepo;
        $this->projectRepo = $projectRepo;
        $this->masterProjRepo = $masterProjRepo;
    }

    public function index(Request $request)
    {
        //dd($request->search_key);
        $clients = $this->clientRepo->displayClients($request);

        return view('admin.client.index', compact('clients'));
    }

    public function create()
    {
        $clients = $this->clientRepo->getAllExceptMaster();

        return view('admin.client.create', compact('clients'));
    }

    public function edit(Client $client)
    {
        $clients = $this->clientRepo->getAllExceptAndNoMaster($client->id);
        $tmpClients = $this->getTempClients($client, $clients);
        $tmpProjects = $this->getTempProjects($client);

        return view('admin.client.edit', compact('client', 'clients', 'tmpClients', 'tmpProjects'));
    }

    public function store(Request $request)
    {
        try
        {
            $client = $this->clientRepo->createClient($request);

            return redirect()->route('admin.clients.index')
                ->withSuccess(__('validation.clients.create', ['prefix' => 'Client']));
        }
        catch (ValidationException $e)
        {
            return $this->redirectFormRequest($e);
        }
    }

    public function update(Request $request, Client $client)
    {
        try
        {
            $client = $this->clientRepo->updateClient($request, $client);

            return redirect()->back()
                ->withSuccess(__('validation.request.update', ['prefix' => 'Client']));
        }
        catch (ValidationException $e)
        {
            return $this->redirectFormRequest($e);
        }
    }

    public function destroy(Client $client)
    {
        try
        {

            $client = $this->clientRepo->deleteClient($client);

            return redirect()->back()
                ->withSuccess(__('validation.request.deleted', ['prefix' => 'Client']));
        }
        catch (ValidationException $e)
        {
            return $this->redirectFormRequest($e);
        }
    }

    public function clientAjax(Request $request)
    {
        //$projects = $this->projectRepo->getByClient($client_ids);
        $projects = Project::where('client_id', $request->client_ids)->get();
        $clients = $this->clientRepo->getByID($request->client_ids);

        $view = view('templates.client.client_projects', compact('projects','clients'))->render();

        return response()->json(['html'=>$view]);
    }

    public function getTempClients($client, $selectClients)
    {
        $tmpClients = array();

        if( $client->exists )
        {
            foreach( $client->clientMasterProjects as $clientMaster )
            {
                $tmpClients[$clientMaster->client_id]['id'] = $clientMaster->client_id;
                $tmpClients[$clientMaster->client_id]['name'] = $clientMaster->client->name;
                $tmpClients[$clientMaster->client_id]['selected'] = true;
            }

            foreach ( $selectClients as $pkey => $selectClient )
            {
                if( !array_key_exists($selectClient->id, $tmpClients) )
                {
                    $tmpClients[$selectClient->id]['id'] = $selectClient->id;
                    $tmpClients[$selectClient->id]['name'] = $selectClient->name;
                    $tmpClients[$selectClient->id]['selected'] = false;
                }
            }
        }

        return $tmpClients;
    }

    public function getTempProjects($client)
    {
        $tmpArr = array();

        if( $client->exists )
        {
            $selectedClientID = array();
            foreach( $client->clientMasterProjects as $clientMaster )
            {
                array_push($selectedClientID, $clientMaster->client_id);
            }

            $clients = $this->clientRepo->getByID($selectedClientID);

            foreach( $clients as $key => $dataClient )
            {
                $projects = $this->projectRepo->getByClient($dataClient->id);

                if( $projects->count() > 0 )
                {
                    $tmpArr[$key]['client']['id'] = $dataClient->id;
                    $tmpArr[$key]['client']['name'] = $dataClient->name;

                    foreach( $projects as $key2 => $project )
                    {
                        $tmpArr[$key]['projects'][$key2]['id'] = $project->id;
                        $tmpArr[$key]['projects'][$key2]['name'] = $project->name;
                        $queriedProj = $this->masterProjRepo->getByMasterProject($project->id, $client->id);

                        if( count($queriedProj) > 0 )
                        {
                            $tmpArr[$key]['projects'][$key2]['selected'] = true;
                        }
                    }
                }
            }
        }

        return $tmpArr;
    }
}

app/Http/Controllers/Client/Project/ProjectsController.php
<?php

namespace App\Http\Controllers\Client\Project;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;
use PermitExpress\Project\Project;
use PermitExpress\Project\ProjectRepository;
use PermitExpress\Validation\ValidationException;

class ProjectsController extends Controller
{
    //
    public function __construct(
        ProjectRepository $projectRepo
    )
    {
        $this->projectRepo = $projectRepo;
    }

    public function index( Request $request )
    {
        $request['client_id'] = Auth::user()->client->id;
        $request['show_to_client'] = true;
        $projects = $this->projectRepo->displayProjects($request);

        return view('client.project.index', compact('projects'));
    }

    public function viewProject(Project $project)
    {
        if($project->client_id != Auth::user()->client->id)
        {
            return redirect()->route('client.projects.index')
                ->withErrors(__('auth.account.unauthorized'));
        }
        return view('client.project.view', compact('project'));
    }

    public function dashboard(Request $request)
    {
        return redirect()->route('client.projects.index');
    }
}

app/Http/Controllers/Client/User/ProfileController.php
<?php

namespace App\Http\Controllers\Client\User;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Http\Controllers\Controller;
use PermitExpress\Client\Client;
use PermitExpress\Client\ClientRepository;
use PermitExpress\User\User;
use PermitExpress\User\UserRepository;
use PermitExpress\Validation\ValidationException;

class ProfileController extends Controller
{
    //
    public function __construct(
        ClientRepository $clientRepo
    )
    {
        $this->clientRepo = $clientRepo;
    }

    public function edit()
    {
        return view('client.user.profile');
    }

    public function update(Request $request, Client $client)
    {
        try
        {
            $client = $this->clientRepo->updateProfile($request, $client);

            return redirect()->back()
                ->withSuccess(__('validation.request.update', ['prefix' => 'Client']));
        }
        catch (ValidationException $e)
        {
            return $this->redirectFormRequest($e);
        }
    }
}

resources/views/admin/client/create.blade.php
@extends('layouts.default')

{{-- Page title --}}
@section('title')
    Add Client
@stop

@section('crumbs')
    <li class="breadcrumb-item">
        <a href="{{ route('admin.clients.index') }}">Clients</a>
    </li>
    <li class="breadcrumb-item active">Add Client</li>
@stop

@section('content')

    @include('templates.client.form', [
        'client' =>  new PermitExpress\Client\Client(),
        'method' => 'POST',
        'actionLabel' => 'Save Client',
        'cardLabel' => 'Company Details',
        'credsLabel' => 'Login Details',
        'contactLabel' => 'Contact Person Details',
    ])

@endsection

resources/views/admin/client/edit.blade.php
@extends('layouts.default')

{{-- Page title --}}
@section('title')
    Edit Client
@stop

@section('crumbs')
    <li class="breadcrumb-item">
        <a href="{{ route('admin.clients.index') }}">Clients</a>
    </li>
    <li class="breadcrumb-item active">Update Client</li>
@stop

@section('content')

    @include('templates.client.form', [
        'client' =>  $client,
        'method' => 'POST',
        'actionLabel' => 'Save Changes',
        'cardLabel' => 'Company Details',
        'credsLabel' => 'Login Details',
        'contactLabel' => 'Contact Person Details',
    ])

@endsection

resources/views/admin/client/index.blade.php
@extends('layouts.default')

{{-- Page title --}}
@section('title')
    Clients
@stop

{{-- Page Breadcrumbs --}}
@section('crumbs')
    <li class="breadcrumb-item active">Clients</li>
@stop

@inject('clientRepo', 'PermitExpress\Client\ClientRepository')

@section('content')
    <div class="row">
        <div class="col">
            <div class="page-title">
                <h1>Clients</h1>
            </div>
            <div class="card m-t-15">
                <div class="card-body flip-scroll">
                    <div class="filter-and-button-wrapper">
                        <div class="row">
                            <div class="col-12 col-md-6">
                                @include('templates.client.filter', [
                                    'method' => 'GET',
                                ])
                            </div>
                            <div class="col-12 col-md-6">
                                <div class="add-wrap">
                                    <a href="{{ route('admin.clients.create') }}" class="btn btn-success btn-add"><i class="fa fa-user-plus"></i> Add Client</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card m-t-15">
                <div class="card-body">
                    <div class="m-t-0">
                        <table class="table table-bordered table-striped" id="index-table" data-sortindex="3" data-sortby="desc" data-disableCol="7">
                            <thead>
                                <tr>
                                    <th>Client Name</th>
                                    <th>Contact Name</th>
                                    <th>Contact Number</th>
                                    <th>Date Created</th>
                                    <th>Projects Created</th>
                                    <th>Access Level</th>
                                    <th class="center-action">Status</th>
                                    <th class="center-action">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse( $clients as $client )
                                    <tr>
                                        <td>
                                            <a href="{{ route('admin.clients.edit', $client) }}" class="tbl-title-link">
                                                {{ $client->name }}
                                            </a>
                                        </td>
                                        <td>{{ $client->cp_first_name . ' ' . $client->cp_last_name }}</td>
                                        <td>{{ $client->cp_number ? $client->cp_number : $client->cp_number_2 }}</td>
                                        <td>{{ $client->created_at->format('F d, Y') }}</td>
                                        <td>{{ $client->projects->count() }}</td>
                                        <td>{{ ($client->is_master) ? 'Master' : 'Client' }}</td>
                                        <td class="center-action"><span class="status {{ $client->user->statusColor }}">{{ $client->user->status }}</span></td>
                                        <td class="center-action">
                                            <a href="{{ route('admin.clients.edit', $client) }}" class="btn btn-success btn-action">EDIT</a>
                                            <a href="{{ route('admin.projects.byClient', $client) }}" class="btn btn-primary btn-action {{ (!$client->is_master) ?: 'disabled' }}">PROJECTS</a>
                                            <a href="{{ route('admin.clients.destroy', $client) }}" class="btn btn-danger btn-action btn-delete"
                                                data-projCount="{{ $clientRepo->hasProjects($client) }}">DELETE</a>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="8">No clients found</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection