routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@manageRedirect');

Route::get('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();


Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth.admin']], function() {

    Route::get('', 'Dashboard\DashboardController@dashboard');
    Route::get('dashboard', 'Dashboard\DashboardController@index')->name('dashboard');

    Route::get('settings', 'Setting\SettingsController@index')->name('settings');
    Route::post('settings', 'Setting\SettingsController@store')->name('store_settings');
    Route::post('settings/{siteSetting}', 'Setting\SettingsController@update')->name('update_settings');

    Route::group(['prefix' => 'clients', 'as' => 'clients.', 'namespace' => 'Client'], function() {

        Route::get('/', 'ClientsController@index')->name('index');

        Route::get('create', 'ClientsController@create')->name('create');
        Route::post('create', 'ClientsController@store')->name('store');

        Route::get('edit/{client}', 'ClientsController@edit')->name('edit');
        Route::post('edit/{client}', 'ClientsController@update')->name('update');

        Route::get('delete/{client}', 'ClientsController@destroy')->name('destroy');

        Route::post('client/ajax', 'ClientsController@clientAjax')->name('client-ajax');

    });

    Route::group(['prefix' => 'cities', 'as' => 'cities.', 'namespace' => 'City'], function() {

        Route::get('/', 'CitiesController@index')->name('index');

        Route::get('create', 'CitiesController@create')->name('create');
        Route::post('create', 'CitiesController@store')->name('store');

        Route::get('edit/{city}', 'CitiesController@edit')->name('edit');
        Route::post('edit/{city}', 'CitiesController@update')->name('update');

        Route::get('delete/{city}', 'CitiesController@destroy')->name('destroy');

    });

    Route::group(['prefix' => 'permits', 'as' => 'permits.', 'namespace' => 'Permit'], function() {

        Route::get('/', 'PermitsController@index')->name('index');

        Route::get('create', 'PermitsController@create')->name('create');
        Route::post('create', 'PermitsController@store')->name('store');

        Route::get('edit/{permit}', 'PermitsController@edit')->name('edit');
        Route::post('edit/{permit}', 'PermitsController@update')->name('update');

        Route::get('delete/{permit}', 'PermitsController@destroy')->name('destroy');

    });

    Route::group(['prefix' => 'permit-categories', 'as' => 'permit_categories.', 'namespace' => 'Permit'], function() {

        Route::get('/', 'PermitCategoriesController@index')->name('index');

        Route::post('quick-create', 'PermitCategoriesController@quickCreate')->name('quick-create');

        Route::get('create', 'PermitCategoriesController@create')->name('create');
        Route::post('create', 'PermitCategoriesController@store')->name('store');

        Route::get('edit/{permitCategory}', 'PermitCategoriesController@edit')->name('edit');
        Route::post('edit/{permitCategory}', 'PermitCategoriesController@update')->name('update');

        Route::get('delete/{permitCategory}', 'PermitCategoriesController@destroy')->name('destroy');

    });

    Route::group(['prefix' => 'users', 'as' => 'users.', 'namespace' => 'User'], function() {

        Route::get('/', 'UsersController@index')->name('index');

        Route::get('create', 'UsersController@create')->name('create');
        Route::post('create', 'UsersController@store')->name('store');

        Route::get('edit/{user}', 'UsersController@edit')->name('edit');
        Route::post('edit/{user}', 'UsersController@update')->name('update');

        Route::get('delete/{user}', 'UsersController@destroy')->name('destroy');

    });

    Route::group(['prefix' => 'projects', 'as' => 'projects.', 'namespace' => 'Project'], function() {

        Route::get('/', 'ProjectsController@index')->name('index');

        Route::get('client-projects/{client}', 'ProjectsController@viewByClient')->name('byClient');

        Route::get('{client}/create', 'ProjectsController@createByClient')->name('createByClient');
        Route::post('{client}/create', 'ProjectsController@storeByClient')->name('createByClient');

        Route::get('create', 'ProjectsController@create')->name('create');
        Route::post('create', 'ProjectsController@store')->name('store');

        Route::get('edit/{project}', 'ProjectsController@edit')->name('edit');
        Route::post('edit/{project}', 'ProjectsController@update')->name('update');

        Route::get('delete/{project}', 'ProjectsController@destroy')->name('destroy');

        Route::post('ajax', 'ProjectsController@permitAjax')->name('permit-ajax');

        Route::post('send-notif', 'ProjectsController@ajaxSendNotification')->name('sendNotif');

        Route::post('delete/file', 'ProjectsController@ajaxDeleteFile')->name('delete-file');

    });

    Route::group(['prefix' => 'reports', 'as' => 'reports.', 'namespace' => 'Report'], function() {

        Route::get('projects-created-per-permit-category', 'ReportsController@projectsPerCategory')->name('projPerCategory');

        Route::get('projects-created', 'ReportsController@viewProjectsCreated')->name('projCreated');

        Route::get('projects-per-city', 'ReportsController@projectsPerCity')->name('projPerCity');

        Route::get('projects-per-status', 'ReportsController@projectsPerStatus')->name('projPerStatus');

    });

});

Route::group(['prefix' => 'client', 'as' => 'client.', 'namespace' => 'Client', 'middleware' => ['auth.client']], function() {

    Route::get('', 'Project\ProjectsController@dashboard')->name('dashboard');

    Route::get('profile', 'User\ProfileController@edit')->name('profile');
    Route::post('profile/{client}', 'User\ProfileController@update')->name('update');

    Route::group(['prefix' => 'projects', 'as' => 'projects.', 'namespace' => 'Project'], function() {

        Route::get('/', 'ProjectsController@index')->name('index');

        Route:: get('view/{project}', 'ProjectsController@viewProject')->name('view');
    });

});

Route::group(['prefix' => 'master-client', 'as' => 'master_client.', 'namespace' => 'MasterClient', 'middleware' => ['auth.master_client']], function() {

    Route::get('', 'Dashboard\DashboardController@dashRedirect')->name('dash-redirect');

    Route::get('dashboard', 'Dashboard\DashboardController@dashboard')->name('dashboard');

    Route::get('profile', 'User\ProfileController@edit')->name('profile');
    Route::post('profile/{client}', 'User\ProfileController@update')->name('update');

    Route::get('clients', 'Dashboard\DashboardController@index')->name('clients');

});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function isActive()
    {
        return $this->active ? true : false;
    }
}

app/Http/Controllers/Admin/User/UsersController.php
<?php

namespace App\Http\Controllers\Admin\User;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Http\Controllers\Controller;
use PermitExpress\User\User;
use PermitExpress\User\UserRepository;
use PermitExpress\Validation\ValidationException;

class UsersController extends Controller
{
    //
    public function __construct(
        UserRepository $userRepo
    )
    {
        $this->userRepo = $userRepo;
    }

    public function index(Request $request)
    {
        $request['except_auth'] = true;
        $users = $this->userRepo->displayUsers($request);

        return view('admin.user.index', compact('users'));
    }

    public function create()
    {
        return view('admin.user.create');
    }

    public function edit(User $user)
    {
        return view('admin.user.edit', compact('user'));
    }

    public function store(Request $request)
    {
        try
        {
            $user = $this->userRepo->createUser($request);

            return redirect()->route('admin.users.index')
                ->withSuccess(__('validation.request.create', ['prefix' => 'User']));
        }
        catch (ValidationException $e)
        {
            return $this->redirectFormRequest($e);
        }
    }

    public function update(Request $request, User $user)
    {
        try
        {
            $user = $this->userRepo->updateUser($request, $user);

            return redirect()->back()
                ->withSuccess(__('validation.request.update', ['prefix' => 'User']));
        }
        catch (ValidationException $e)
        {
            return $this->redirectFormRequest($e);
        }
    }

    public function destroy(User $user)
    {
        try
        {
            $user = $this->userRepo->deleteUser($user);

            return redirect()->back()
                ->withSuccess(__('validation.request.deleted', ['prefix' => 'User']));
        }
        catch (ValidationException $e)
        {
            return $this->redirectFormRequest($e);
        }
    }
}

app/Http/Controllers/Client/User/ProfileController.php
<?php

namespace App\Http\Controllers\Client\User;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Http\Controllers\Controller;
use PermitExpress\Client\Client;
use PermitExpress\Client\ClientRepository;
use PermitExpress\User\User;
use PermitExpress\User\UserRepository;
use PermitExpress\Validation\ValidationException;

class ProfileController extends Controller
{
    //
    public function __construct(
        ClientRepository $clientRepo
    )
    {
        $this->clientRepo = $clientRepo;
    }

    public function edit()
    {
        return view('client.user.profile');
    }

    public function update(Request $request, Client $client)
    {
        try
        {
            $client = $this->clientRepo->updateProfile($request, $client);

            return redirect()->back()
                ->withSuccess(__('validation.request.update', ['prefix' => 'Client']));
        }
        catch (ValidationException $e)
        {
            return $this->redirectFormRequest($e);
        }
    }
}

app/Http/Controllers/MasterClient/User/ProfileController.php
<?php

namespace App\Http\Controllers\MasterClient\User;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Http\Controllers\Controller;
use PermitExpress\Client\Client;
use PermitExpress\Client\ClientRepository;
use PermitExpress\User\User;
use PermitExpress\User\UserRepository;
use PermitExpress\Validation\ValidationException;

class ProfileController extends Controller
{
    //
    public function __construct(
        ClientRepository $clientRepo
    )
    {
        $this->clientRepo = $clientRepo;
    }

    public function edit()
    {
        return view('master_client.user.profile', compact('client'));
    }

    public function update(Request $request, Client $client)
    {
        try
        {
            $client = $this->clientRepo->updateProfile($request, $client);

            return redirect()->back()
                ->withSuccess(__('validation.request.update', ['prefix' => 'Client']));
        }
        catch (ValidationException $e)
        {
            return $this->redirectFormRequest($e);
        }
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.default')

{{-- Page title --}}
@section('title')
    Add User
@stop

@section('crumbs')
    <li class="breadcrumb-item">
        <a href="{{ route('admin.users.index') }}">Users</a>
    </li>
    <li class="breadcrumb-item active">Add User</li>
@stop

@section('content')

    @include('templates.user.form', [
        'user' =>  new PermitExpress\User\User(),
        'method' => 'POST',
        'actionLabel' => 'Save User',
        'cardLabel' => 'Details'
    ])

@endsection

resources/views/admin/user/edit.blade.php
@extends('layouts.default')

{{-- Page title --}}
@section('title')
    Edit User
@stop

@section('crumbs')
    <li class="breadcrumb-item">
        <a href="{{ route('admin.users.index') }}">Users</a>
    </li>
    <li class="breadcrumb-item active">Update User</li>
@stop

@section('content')

    @include('templates.user.form', [
        'user' =>  $user,
        'method' => 'POST',
        'actionLabel' => 'Save Changes',
        'cardLabel' => 'Details'
    ])

@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.default')

{{-- Page title --}}
@section('title')
    Users
@stop

{{-- Page Breadcrumbs --}}
@section('crumbs')
    <li class="breadcrumb-item active">Users</li>
@stop

@section('content')
    <div class="row">
        <div class="col">
            <div class="page-title">
                <h1>Users</h1>
            </div>
            <div class="card m-t-15">
                <div class="card-body flip-scroll">
                    <div class="filter-and-button-wrapper">
                        <div class="row">
                            <div class="col-12 col-md-6">
                                @include('templates.user.filter', [
                                    'method' => 'GET',
                                ])
                            </div>
                            <div class="col-12 col-md-6">
                                <div class="add-wrap">
                                    <a href="{{ route('admin.users.create') }}" class="btn btn-success btn-add"><i class="fa fa-plus"></i> Add User</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card m-t-15">
                <div class="card-body flip-scroll">
                    <div class="m-t-0">
                        <table class="table table-bordered table-striped flip-content" id="index-table" data-sortindex="3" data-sortby="desc" data-disableCol="4">
                            <thead class="flip-content">
                            <tr>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Username</th>
                                <th>Date Created</th>
                                <th class="center-action">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                                @forelse( $users as $user )
                                    <tr>
                                        <td>
                                            <a href="{{ route('admin.users.edit', $user) }}" class="tbl-title-link">
                                                {{ $user->first_name . ' ' . $user->last_name }}
                                            </a>
                                        </td>
                                        <td>{{ $user->email }}</td>
                                        <td>{{ $user->username }}</td>
                                        <td>{{ ($user->created_at) ? $user->created_at->format('F d, Y') : '-/--/--' }}</td>
                                        <td class="center-action">
                                            <a href="{{ route('admin.users.edit', $user) }}" class="btn btn-primary btn-action">EDIT</a>
                                            <a href="{{ route('admin.users.destroy', $user) }}" class="btn btn-danger btn-action btn-delete">DELETE</a>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="5">No users found</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection